### ISSUE TITLE
Feature Request:- Add an option to enable blur in App Drawer

### ISSUE THREAD

**Issue by MrigendraB** [NeoApplications/Neo-Launcher#102]
It is great that the app has Blur option for it's Settings and kinda in Dock Background too.

But it would be great addition if we would be able to add blur in App Drawer too (or may be in pop up menu too).

**Comment by Aman9das** [comment]
Changing drawer opacity from auto or 100, shows the blur effect underneath, so I suppose you have set the drawer opaque..

**Comment by nonetrix** [comment]
I cannot find opacity setting only can find it in the dock?

**Comment by machiav3lli** [comment]
@nonetrix  Already added, but not released yet

**Comment by nonetrix** [comment]
Understood I'll watch this repo for next release for now much appreciated keep up good work
