### ISSUE TITLE
feature request: magisk module

### ISSUE THREAD

**Issue by Sinasta** [NeoApplications/Neo-Launcher#106]
Hello there Great work! Thank you! Would it be possible to pack this launcher in an Magisk module so that it can replace the stock launcher systemlessly?

**Comment by Sinasta** [comment]
maybe i should explain why i would like that feature: like this i would be able to remove the stock launcher without having to install quickstep for the rescents to work. Just like shadylauncher ( https://www.pling.com/p/1376074/ )

**Comment by saulhdev** [comment]
Quick switch not being maintained or developed
