### ISSUE TITLE
Weird home return animation

### ISSUE THREAD

**Issue by J4gQBqqR** [NeoApplications/Neo-Launcher#108]
## Description

I set Omega Launcher as default launcher in Android setting and "Quick switch" https://github.com/skittles9823/QuickSwitch

## Expected Behavior
Normal animation.

## Actual Behavior

The icons are off placed in animation. Center piece of icon is shown outside of the adaptive icon box on a lower position. It is also distorted in shape.

## Steps to Reproduce
https://youtu.be/SYlEhg0DJ3w

## Device and OS

* Device: OnePlus 7 pro
* Android version: 11
* Launcher version: 0.8.1
* Rom: Lineage OS 18.1

**Comment by saulhdev** [comment]
Quick switch not being developed or maintained.
