### ISSUE TITLE
[feature request] Add optional date bar

### ISSUE THREAD

**Issue by GithubUser699** [NeoApplications/Neo-Launcher#121]
## Description

I would like to have a date bar similar to the one open launcher (com.benny.openlauncher) has. 
![2_OpenLauncher](https://user-images.githubusercontent.com/74927253/135542019-07434f30-5585-421a-8cf4-e59acb468755.png)
In Openlauncher this date bar is accessible from every  desktop site and tapping on it will open the calendar app.
You can choose the date format and text color via the settings:
![3_OpenLauncher](https://user-images.githubusercontent.com/74927253/135542233-25fae5e7-cbb2-4a30-a805-c8bd86a54a3e.png)
![4_OpenLauncher](https://user-images.githubusercontent.com/74927253/135542245-e5c543c5-28b6-40d5-bcc0-d60922a2360f.png)
![5_OpenLauncher](https://user-images.githubusercontent.com/74927253/135542257-af3d69ea-ea77-4b82-aa9a-437fa70f3bf1.png)
![6_OpenLauncher](https://user-images.githubusercontent.com/74927253/135542272-b1f92e65-fe0b-4bf7-96ac-397654847bbd.png)

## Expected Behavior
Such a date bar with the customization options similar to openlauncher would be great.

## Actual Behavior
There is no such date bar. 
![1_Omega_Launcher](https://user-images.githubusercontent.com/74927253/135543973-8410c7fb-f4ea-4478-9f57-4c59305ab3b8.png)
I actually use it a lot, especially the "tab to open calendar" function.

## Steps to Reproduce
/

## Device and OS

Package: com.saggitt.omega 
Version: v0.8.1 (build 280)
Flavor: aospWithQuickstepOmega (release)
Build date: 2021-08-18T00:11Z
ISource: Function0
Manufacturer : Xiaomi
Model : Mi A2
OS Version : Android 11
Rom: LineageOS 18.1

**Comment by otakuhqz** [comment]
The current clock widget works if you have the Google App installed. If the Google app is installed, then go to Settings > Home Widget > Show Smartspace.

**Comment by machiav3lli** [comment]
@otakuhqz maybe we can combine this with the work on the side shelf

**Comment by GithubUser699** [comment]
@machiav3lli, may I ask if you're still working on it?

**Comment by GithubUser699** [comment]
It's doesn't support custom date formats and text colors though, does it?
@saulhdev @machiav3lli
