### ISSUE TITLE
[Feature request] Add quick settings toggle widget

### ISSUE THREAD

**Issue by Sitavi** [NeoApplications/Neo-Launcher#125]
I suggest to add littles shortcuts widgets (same size as app icon) to toggle airplane mode, mobile data, bluetooth, wifi, and to lock the screen. It would be so useful!

MIUI example:
![IMG_20211005_000858](https://user-images.githubusercontent.com/80586127/135931830-a1111f76-450f-4544-9a13-1f8ceec3a372.jpg)

**Comment by saulhdev** [comment]
added a preference to choose the size for each tile
