### ISSUE TITLE
Changing the first app in a folder with Covers enabled breaks the folder

### ISSUE THREAD

**Issue by Victor239** [NeoApplications/Neo-Launcher#130]
## Description
I mainly use folders with Covers on another launcher and am trying to swap to Omega. I cannot reliability swap the order of the first app in a folder with Covers enabled, because it won't show the icon of the new first app and any attempt to fix this will break the folder.

## Expected Behavior
Swapping the first app in a folder with Covers enabled should change the icon to that app, and it shouldn't break in multiple ways after. 

## Actual Behavior
The Covers icon remains that of the previous first app in the folder, and trying to fix that results in a broken folder. 

## Steps to Reproduce
1) Change a folder with 2 apps in it into Covers (App-A and App-B)
2) Reorder the apps, so that the 2nd app (App-B) is now the first (and therefore should be the new Cover)
3) Observe that this fails - App-A is still the Cover despite being the second app in the folder

4) Turn Cover mode off on the folder
5) Observe that the whole Cover goes invisible when you attempt to click on it
6) Clicking elsewhere on the desktop will reset it to looking like a folder, but clicking on it again will still just make it invisible. Swiping on it as if it were a Cover does nothing

## Device and OS

* Device: Xiaomi Pocophone F1
* Android version: 11
* Launcher version: 0.8.1
* Rom: LineageOS 18.1

**Comment by saulhdev** [comment]
Fixed on v0.9.1
