### ISSUE TITLE
[Reopen] Recents crash when Omega is preinstalled on A12

### ISSUE THREAD

**Issue by LeOS-GSI** [NeoApplications/Neo-Launcher#133]
The original Launcher3Quickstep has 'recent button features'. These features are missing in the Omega Quickstep.

If you will include the recent button features in Omega, I will donate 50 Euro for you.

--------------------------------------------------------------
I have to reopen this request #119 , because on Android12 when Omega Launcher is included in the ROM/GSI the launcher will crashing all the time. I think the root cause is, that Launcher3Qucikstep and Omega Launcher will use same resources. 
So if Omega Launcher includes the 'recent button' gestures which is defined in Quickstep no need to have both Launchers in ROM/GSI. 

So, please include the recent button gestures in Omega. Thx.

**Comment by machiav3lli** [comment]
The latest release of Omega 0.8.2 is based on A11's launcher3 and though may have such issues. We're working now on rebasing to A12. The quickstep maintainence is seen by us as wasted time as generally system's recent's provider include that and Omega is used just a launcher. Some users reported some issues when setting Omega as a recent provider using Quickswitch and for us debugging those is a time consuming process which we decided to avoid. Should things be easier with the new base, then I don't see a problem fixing some more simple issues.

**Comment by LeOS-GSI** [comment]
I'm sorry, but that's wrong. In my LeOS-GSI group we have hundreds of different devices where the recent button is dead if Launcher3Quickstep is not installed. All these tons of devices needing the recent button  gestures which are defined in Quickstep.

And yes, Quickstep is still crashing on A12, not only when preinstalled, also when it is installed later.

**Comment by machiav3lli** [comment]
I understand your point, but Omega isn't/wasn't planned to be a built-in launcher and peace launcher (LeOS-launcher) is nothing but I direct fork that isn't adapted (back) to be a pre-built launcher.

The main use case of Omega in its direct community is being an installed(user) launcher and that's why we consider(ed) this issue as not important. All I can say, just wait for us to bring up A12 base, this could maybe solve your issue.

**Comment by saulhdev** [comment]
we are not longer working any recents feature
