### ISSUE TITLE
[Request] Searx searvice in search bar

### ISSUE THREAD

**Issue by taxbax** [NeoApplications/Neo-Launcher#137]
https://searx.me/

Searx is a free internet metasearch engine which aggregates results from more than 70 search services. Users are neither tracked nor profiled. Additionally, searx can be used over Tor for online anonymity.

Get started with searx by using one of the Searx-instances. If you don’t trust anyone, you can set up your own.

**Comment by machiav3lli** [comment]
The text doesn't make much sense as a feature rewuest but anyway. We already have implemented a public instance of searx in Omega and in the future there'll be option to configure your search provider.

**Comment by taxbax** [comment]
Amazing!

**Comment by saulhdev** [comment]
Added on v0.9 beta 1
