### ISSUE TITLE
Opening categories in App Drawer causes Omega to hang and crash.

### ISSUE THREAD

**Issue by doidge-kyle** [NeoApplications/Neo-Launcher#148]
Build: 0.8.1
Device: Pixel 5
Android version: 12

I have multiple app categories in my app drawer that I had working previously (I was not up to the version number even before the most recent though, don't recall which one). Since updating to the most recent version, tapping the app category bubble freezes Omega then I'm told by Android that Omega is no longer responding.

**Comment by DarthPleurotus** [comment]
@doidge-kyle what version were you using previously? I am having the same issue and would like to roll back to an earlier version while this is getting resolved

**Comment by DarthPleurotus** [comment]
It's worth mentioning that this is my favorite FOSS Android launcher- this is the only real issue that I have found with it

**Comment by machiav3lli** [comment]
What type of apps are in the mentioned category? And are you using work profile?

**Comment by doidge-kyle** [comment]
@DarthPleurotus I dont recall what version it was because I had gotten the APK direct from github and not from F-Droid where I currently get it and the APK file has been cleared from my phone.

@machiav3lli all types of apps considering it happens to any of them.

**Comment by saulhdev** [comment]
Fixed on v0.9.0
