### ISSUE TITLE
[Feature Request] App Recall or Recent App 

### ISSUE THREAD

**Issue by Tech-e1** [NeoApplications/Neo-Launcher#151]
## Description

Often users don't simply use one app at a time. There involves toggling and even split screen activity to get work done. 

## Expected Behavior

One should expect that the app recall button displays the most recent apps used before they are killed. Preferably with preview capability. 

## Actual Behavior

The app recall button is rendered useless in the latest version of the launcher. Apps can only be used one at a time. 

## Steps to Reproduce

1.Press app recall button
2.
3.
4.

## Device and OS

* Device: Moto G7
* Android version: 10
* Launcher version:v0.8.1 (build 280)
on Aug 17, 2021
* Rom: Stock Rom

## Logcat

```
your log here
```

**Comment by machiav3lli** [comment]
If you mean supporting quickstep, then you can read #133 and close this, as we don't support quickstep for now. Otherwise please be more precise about what you wish/suggest.

**Comment by saulhdev** [comment]
Close as didn't get more information
