### ISSUE TITLE
add the ability to change the amount of icons in the dock and drawer, currently it only shows rows of 4 icons

### ISSUE THREAD

**Issue by Rafael2616** [NeoApplications/Neo-Launcher#153]
This Launcher is excellent, congratulations for the work, unique features and perfect fluidity!

**Comment by machiav3lli** [comment]
While reporting please provide more relevant info e.g. what version are you using?

**Comment by Rafael2616** [comment]
Sorry, I'm using Android 9, and the performance is cool!! but the app crashes when adding widgets

**Comment by saulhdev** [comment]
Already added on v0.9 beta 1
