### ISSUE TITLE
Import Lawnchair misses settings

### ISSUE THREAD

**Issue by lawson85** [NeoApplications/Neo-Launcher#161]
Some settings such as hidden apps, icon size and so many others are not imported. 

## Description
The version imported from 2.0-2589

## Expected Behavior
Import all settings

## Actual Behavior
Missing settings

## Steps to Reproduce

1. Export settings from the play store version of Lawnchair
2. Import Lawnchair settings into the latest release from Github 0.8.1
3. See error

## Device and OS

* Android version: 10
* Launcher version: 0.8.1 Github
* Rom: EMUI 10.0.0

**Comment by machiav3lli** [comment]
We are not a lawnchair fork and we don't support importing settings from LC. This won't change in the coming versions too.
