### ISSUE TITLE
Support older Android versions

### ISSUE THREAD

**Issue by lawson85** [NeoApplications/Neo-Launcher#162]
## Description
I and others have Android's running 5+ that would like to use this Launcher

## Expected Behavior
Install on A5+

## Actual Behavior
MinSDK is set to A8+ so it's not going to install on A5.

## Device and OS
* Device: Samsung Galaxy core prime
* Android version: 5.1.1
* Launcher version: N/A
* Rom: TouchWiz

* Device: Lenovo Yoga tab 3. 
* Android version: 6.0
* Launcher version: N/A
* Rom: Stock

**Comment by machiav3lli** [comment]
Not really, supporting older Android versions will complicate development too much and the effort isn't worth it!
