### ISSUE TITLE
Icons or widgets won't stays where Dock used to be even it is disabled

### ISSUE THREAD

**Issue by Knud3** [NeoApplications/Neo-Launcher#163]
## Expected Behavior
When Dock is disabled I can use space what it was using.

## Actual Behavior
After launcher is restarted icons and widgets are moved away where Dock used to be.

## Steps to Reproduce
1. Disable Dock
2. Move icon(s) and/or widget(s) bottom of the screen where Dock used to be
3. Restart launcher
4. See your icon(s) and/or widget(s) are moved out like there was Dock

## Device and OS
* Device: Samsung S22
* Android version: 12 (kernel 5.10.66)
* Launcher version: 0.8.1
* Rom: Vanilla

**Comment by machiav3lli** [comment]
Fixed in latest commit
