### ISSUE TITLE
Ransomware

### ISSUE THREAD

**Issue by PaulMcF1987** [NeoApplications/Neo-Launcher#165]
I found this launcher via alternativeto.com
Seems to be exactly what I'm looking for

However, I have a premium malwarebyres subscription and when I installed the launcher malwarebytes instantly flaged it as ransomwaree and advised that I remove it.

Is someone able to shed any light on this?

**Comment by PaulMcF1987** [comment]
@machiav3lli  I doubt it is the play store signature it is looking for as I have allowed install from unknown sources and have "side loaded" other apps and not had this issue.

I cant remember the exact message as I have deleted the APK, but it flagged as potential Ransomware and recommended I delete it.

**Comment by saulhdev** [comment]
Since the name "Neo Launcher" is new and you are installing it from an APK file, you get a warning of the antivirus software or Play Protect. You should not receive that message when you install the next version

@machiav3lli I have a Play Store account, and it will be published when the next stable release is ready.

**Comment by akostadinov** [comment]
Still not published to play? It doesn't also show up in f-droid. No mention in https://en.wikipedia.org/wiki/List_of_Android_launchers

Definitely not something I would install from a random source. Or maybe I just didn't research well. But having it accessible from a reputable source that even ignorant users like me recognize, will help a lot, thanks!

**Comment by machiav3lli** [comment]
@akostadinov it's available on IzzyOnDroid's FDroid repo, the second largest repo
