### ISSUE TITLE
[Feature request] Add more columns and rows in home screen/app drawer

### ISSUE THREAD

**Issue by prismacolorgold** [NeoApplications/Neo-Launcher#167]
## Description
I am coming from Nova Launcher, using Note 8, 10+ and tab 8+. These screens are big and the current limit of this launcher is limited to 9x9 max (Nova 6 has 12x12, but it's still not enough for the 12.4" tab 8+). Can I request more (20 max)? 
![1](https://user-images.githubusercontent.com/19483499/174418514-36c41aed-e6ff-408c-b890-dbf8ccd1d1f0.PNG)

Can I also request to have the ability to close/control the gap between the icons line?  (but allowing more than 9 lines would help me to close the cap between the icons tremulously!)
![Screenshot_20220617-182932_Omega Launcher](https://user-images.githubusercontent.com/19483499/174418524-698417f2-14d0-4caf-838b-104b77b65784.png)
![Screenshot_20220617-182943_Omega Launcher](https://user-images.githubusercontent.com/19483499/174418527-4f3fe1b2-42fc-4ee4-bd6b-12e679a1ccd1.png)

This is the end result I'd like to see (from nova). (I design my own icon, please excuses the newly installed f-droid apps that doesn't follow the style)
![Screenshot_20220617-183407_Nova Launcher](https://user-images.githubusercontent.com/19483499/174418534-649844af-d044-48f1-b0d0-444a97297cc9.jpg)

* Device: Note 8, Note 10+, Tab 8+
* Android version: 9 & 12
* Launcher version: v0.8.1
* Rom: Stock

**Comment by pguenth** [comment]
I would also very much appreciate an increase in the row/column limits. It would be especially useful for more recent, larger phones.

**Comment by Korpip** [comment]
This would be welcomed by me.  I have many things on my home screen.
