### ISSUE TITLE
Notification bubbles are very small

### ISSUE THREAD

**Issue by l3u** [NeoApplications/Neo-Launcher#171]
I'm not sure if this is a bug or a feature ;-)

Neo Launcher is the continuation of Omega Launcher (which before was ZIM Launcher), right?!

I installed Neo Launcher 0.9.0 yesterday. It was no problem to configure it in a way that it largely looked just like my Omega installation. I noticed one thing though:

The notification bubbles are a lot smaller.

Here's Omega:
![omega](https://user-images.githubusercontent.com/6770781/179389757-1bad16f2-9736-4a10-b9fe-856dcc242c45.png)

And here's Neo:
![neo](https://user-images.githubusercontent.com/6770781/179389773-9e4b0f84-4301-40d8-9fbd-ebcabe1b404e.png)

Apparently, this also can't be configured/changed. Is this intended behavior?

**Comment by machiav3lli** [comment]
As Zim (an older project) was, Omega/Neo (same project but newly renamed) are launcher3 based (the AOSP launcher). This is the source of the problem, 0.9.0 is based on the A12 sources (in contrast to the A11-based 0.8.X) which introduced this change, but this can be fixed in an upcoming release.

**Comment by l3u** [comment]
Thanks for the clarification!

The problem seems to depend on the number of notifications though, 13 look quite like before:
![13](https://user-images.githubusercontent.com/6770781/179422953-c617b6bd-31bc-47b7-a97c-6a620bcc7b2e.png)

**Comment by l3u** [comment]
Strangely, the issue is gone after usung Neo Launcher for a time (maybe afte a reboot?!):
![1](https://user-images.githubusercontent.com/6770781/179804642-bf97a537-24a1-4e36-8824-6d311194b002.png)
Maybe this is some initial configuration/initialization problem?
