### ISSUE TITLE
Global search is very slow and buggy

### ISSUE THREAD

**Issue by candroid-man** [NeoApplications/Neo-Launcher#172]
Currently I am using the Brave search engine in the search bar included with the latest version of Neo-Launcher, and I am not impressed. The browser suggestions are weird and never includes what I am typing, app search is slow and doesn't update quickly, and as you are typing a browser search query random apps show up even if there are 3+ words in the search bar.

While suggestions would be nice if they worked correctly, I think I would rather not have them if it would make app search more reliable, and then when you make a search query in the same bar without suggestions.

Edit: Video of my experience (PeerTube): https://tube.tchncs.de/w/2afXtpReGHpSAuvh9Ab2DW

**Comment by saulhdev** [comment]
Duplicated #111

**Comment by candroid-man** [comment]
Whoops, should I remove this or keep this one with the video and better explanation?

**Comment by saulhdev** [comment]
Keep it. We will close both when it is fixed.

**Comment by saulhdev** [comment]
Fixed in commit [713945f](https://github.com/NeoApplications/Neo-Launcher/commit/713945f079352f80db76be07aafddf63dd07d5f7)
