### ISSUE TITLE
Wrong name

### ISSUE THREAD

**Issue by derpyderpaderp** [NeoApplications/Neo-Launcher#175]
Wasn't sure where to report this but the description for fdroid has the wrong name. Not really a bug but figured you would want to be made aware of it.

**Comment by urmomsangus** [comment]
Not OP, but if you look at the description in an F-Droid app, it still shows "Omega Launcher is a fork of..."

**Comment by derpyderpaderp** [comment]
> Can you please provide more details? I checked and it looks correct

![Screenshot_20220719-115421_Droid-ify.jpg](https://user-images.githubusercontent.com/12119604/179807180-2e274d7c-06d2-4744-a86c-8f2cdabbe891.jpg)

**Comment by machiav3lli** [comment]
For context: https://gitlab.com/IzzyOnDroid/repo/-/issues/148
