### ISSUE TITLE
Launcher crash when using 0.9.0

### ISSUE THREAD

**Issue by Offerel** [NeoApplications/Neo-Launcher#177]
## Description
If I install a fresh install of version 0.9.0 , the launcher is chrashing, when i try to start the launcher. There is no previous configuration. Version 0.8.1 is starting without any issue. 

## Expected Behavior
The launcher should start without issues.

## Actual Behavior
Launcher is crashing

## Steps to Reproduce
1. Download release 0.9.0 from Github as APK
2. Install application
3. Start application
4. Application is crashing

## Device and OS
Device: Samsung Galaxy S20
Android version: 12.x
Launcher version: 0.9.0
Rom: OneUI 4.1

**Comment by holdit** [comment]
I can confirm this (LineageOS 18.1/Android 11). Crashes once, then runs fine.

**Comment by Offerel** [comment]
In my case it never starts correctly. Directly after install and with first start, i crashes. After that, the app will never start. I have also tried to re-install and also to reset all settings, but this doesn't help. I always have the same behavior. So i cant use the new version. There was no such issue with 0.8.1.

I have no idea how to create this logfiles, that some other users posted here. If this would help, to identify the issue, i can try to create such file, as long someone tell me how to do that.

**Comment by chloevo** [comment]
I have the same issue on my Samsung Galaxy S9+, Android 10, OneUI 2.5

**Comment by Korpip** [comment]
Fresh install from Fdroid on a stock S10 Snapdragon will not start.

Galaxy S10 (SM-G973W)
Build Number : G973WVLU6IVD3
Android version : S(Android 12)

**Comment by Inovvia** [comment]
Also crashing on my on fresh install, I attached a logfile for reference

Galaxy M51
Android 12

[logs-2022-07-24-17-32-54.zip](https://github.com/NeoApplications/Neo-Launcher/files/9175893/logs-2022-07-24-17-32-54.zip)
l

**Comment by machiav3lli** [comment]
@Inovvia thanks for the logs, it is pretty useful to be able to fix this one-ui-related bug.

If any of the effected people is in the community group, then please write there, so we can provide you with a test build.

**Comment by Korpip** [comment]
The test build from the community group works on my Samsung.

**Comment by Inovvia** [comment]
@machiav3lli I just tested the test build from the telegram group and can confirm that the launcher is now working for me. Thanks!

**Comment by Offerel** [comment]
IS this fix available under actions? I don't have telegram...

**Comment by saulhdev** [comment]
Fixed on v0.9.1
