### ISSUE TITLE
Widget width / space to the side

### ISSUE THREAD

**Issue by Offerel** [NeoApplications/Neo-Launcher#178]
## Description
I don't know if this is more a feature request as a bug. Coming from Action Launcher/Nova Launcher, my widgets are a lot smaller displayed on Omega Launcher as in the other Launchers. Is there some way to have more width of a widget, but NOT use full width?

I have attached screenshots from Nova Launcher, showing the same grid settings and widgets as on Omega Launcher.

## Expected Behavior
![image](https://user-images.githubusercontent.com/14041522/179975593-cc8d63b4-cf3a-477f-a6e5-caaf7d2cbc03.png)

## Actual Behavior
![image](https://user-images.githubusercontent.com/14041522/179975630-f9533f0f-39d0-4bb2-818a-8da7b8830e76.png)

## Device and OS
Device: Samsung Galaxy S20 
Android version: 12.x
Launcher version: 0.8.1
Rom: OneUI 4.1

**Comment by saulhdev** [comment]
v0.8.1 not longer mantained. We are working issues from the new release only
