### ISSUE TITLE
Problems reordering the 'work' tab in app drawer

### ISSUE THREAD

**Issue by Elbullazul** [NeoApplications/Neo-Launcher#179]
## Description
There are some issues reordering the work tab in 'categorize apps'. Whatever changes I make to the order of the tabs, the work tab is always the first in the app drawer.

## Expected Behavior
When I change the order of tabs, the launcher should respect that order

## Actual Behavior
Whenever I change the order of the work tab, a new work tab appears at the desired location, but keeping the a work tab at the previous location too. If I reorder the tabs manu times I end up with many work tabs scattered on the tab list.

Upon restarting the app, the 'new' work tab disappears, but the work tab remains first in the tab list.

## Steps to Reproduce

1. Create a work profile and add some apps
2. Enable app categories in the app drawer
3. Enable 'Work apps in separate tab' option
4. Reorder the tabs and change the work tab position

## Device and OS

* Device: Google Pixel 6 Pro
* Android version: 12
* Launcher version: 0.9.0
* Rom: CalyxOS 3.7.2

**Comment by Elbullazul** [comment]
Here is a screenshot:
![Screenshot_20220721-180600](https://user-images.githubusercontent.com/15310985/180849068-2b07b2a7-4dd9-4d7f-b616-56f810278ec3.png)

**Comment by Tanzeel159** [comment]
Yes I am facing same issue!

**Comment by saulhdev** [comment]
Fixed in commit 9734e3ed
