### ISSUE TITLE
[Feature Request] Toggle in search setting to launch keyboard on Search 

### ISSUE THREAD

**Issue by urmomsangus** [NeoApplications/Neo-Launcher#180]
If I set a gesture to launch App Search or Global search, it would be nice to have the option to automatically open the keyboard when searching.

A toggle in the Search settings to enable this would make the search more powerful.

Thanks

**Comment by MichalSvatos** [comment]
I set up to open **Global search** on swipe up and the keyboard opens automatically 🤔

**Comment by urmomsangus** [comment]
> I set up to open **Global search** on swipe up and the keyboard opens automatically 🤔

Ah, it does work that way for me too, although I thought I tried both options already. Apparently just the app search doesn't open the keyboard.

Not sure if that's the intended behavior or not. I'll close this since I messed up the issue. Devs can reopen if wanted, if app search should open keyboard.
