### ISSUE TITLE
App-Drawer row height & opacity missing in 0.9.0

### ISSUE THREAD

**Issue by FabianMPunkt** [NeoApplications/Neo-Launcher#181]
## Description
As the title says, the option for "row height" and "background opacity" for the app drawer are missing in v0.9.0
I'm a really big fan of  this project but this little annoyance has me stuck on 0.8.1

## Expected Behavior
There should be options for "row height" and "opacity" in 0.9.0

## Actual Behavior
The options "row height" and "opacity" are missing in 0.9.0

## Steps to Reproduce

1. Install NeoLauncher v0.9.0
2. Go to Settings > Drawer
3. row height not present
4. opacity not present

## Device and OS

* Device: Sony Xperia 1 iii "XQ-BC52"
* Android version: 12.0 
* Launcher version: 0.9.0
* Rom: Stock Sony ROM

This is Omega v0.8.1: (60% row height / 85% opacity)
![0.8.1](https://user-images.githubusercontent.com/78741736/180070047-a4dded74-326c-40f2-803a-ef6871d6ab4a.png)

This is Neo v0.9.0:
![0.9.0](https://user-images.githubusercontent.com/78741736/180070077-b776869f-888c-49e5-8a8d-930b3531a126.png)

**Comment by GoldenAureuz** [comment]
What happened to those features? Drawer transparency was one of my favorite features in this launcher.

**Comment by saulhdev** [comment]
both features had been added in the current development version.
