### ISSUE TITLE
Add style options for folders

### ISSUE THREAD

**Issue by candroid-man** [NeoApplications/Neo-Launcher#184]
Coming from Ruthless Launcher, I am used to the folders looking like this (which I prefer):

![Screenshot_20220720-205608.png](https://user-images.githubusercontent.com/51019003/180113171-2c90aa8b-85d7-4c50-b989-63f5c772cd97.png)

This is the closest I could get using Neo Launcher:

![Screenshot_20220720-205545.png](https://user-images.githubusercontent.com/51019003/180113207-f7289ee5-a936-4b63-914d-39af8d57c735.png)

Maybe add some folder style options to, for example, add borders or perhaps even changing the folder to an icon from your icon pack

**Comment by holdit** [comment]
It would also be nice to have opacity/transparency support.

Completely white or grey folders don't look nice with some wallpapers.

**Comment by saulhdev** [comment]
V1.0 already include stroke customization, background and opacity.
