### ISSUE TITLE
Folder disappears when adding too many apps

### ISSUE THREAD

**Issue by holdit** [NeoApplications/Neo-Launcher#186]
## Description

Folders with many apps (more than one "page") sometimes disappear when adding another app. When this happens, the folder disappears and only one app stays (the first one) in its place.

## Expected Behavior

Folders shouldn't delete themselves. 

## Actual Behavior

Folders delete themselves after a certain limit. This is not a fixed limit as sometimes I can get ~20 apps, but sometimes it's less.

## Steps to Reproduce

1. Create a folder
2. Keep adding apps (can be the same one multiple times)
3. Eventually the folder will disappear, leaving only one app in its place

## Device and OS

* Android version: 11
* Launcher version: 0.9.0
* Rom: LineageOS 18.1

**Comment by machiav3lli** [comment]
It doesn't disapper, it activates cover mode. Swip up on the icon to open the folder!

**Comment by holdit** [comment]
@machiav3lli I wasn't aware, thanks.

In that case, may I suggest that the feature is described somewhere (can't find anything about it in the app or on the main page of this repo) or at least that cover mode isn't trigged automatically.

I've never seen this feature before, there was no warning of what had happen, it didn't look like a folder anymore, etc, so I assumed it was a bug.

**Comment by holdit** [comment]
I've been testing and even after manually disabling cover mode, it seems to enable it after some time or when I make changes to my home screen.

**Comment by userliluzibert** [comment]
Yeah I can't find a solution to it. I hope there's a solution to this. I guess after a certain amount of apps it forces cover mode on the folder.

**Comment by saulhdev** [comment]
This issue is fixed on the version 0.9.1
