### ISSUE TITLE
Open App Gesture Not Allowing Option to Choose App

### ISSUE THREAD

**Issue by PollingK** [NeoApplications/Neo-Launcher#194]
## Description
When applying the Open App option to any gesture (Double tap, Swipe down, Swipe up, etc) there is no option to select which app to open. 

## Expected Behavior
When downgrading to version 0.8.1, the Open App gesture works correctly. Upon selecting the Open App option, a list of available apps can be selected.

## Actual Behavior
No list appears, when attempting the gesture on the home screen. Nothing occurs.

## Device and OS
* Device: OnePlus 3
* Android version: 11
* Launcher version: 0.9.0
* Rom: LineageOS 18.1

**Comment by saulhdev** [comment]
Fixed in commit 2933f16f
