### ISSUE TITLE
Feature request: Widget wall or RSS feed as  Google Discover alternatives

### ISSUE THREAD

**Issue by nodeunit** [NeoApplications/Neo-Launcher#199]
This is an idea for far in the future, pie-in-the-sky possibilities;

As some of us no longer use the Google app to get our news, it would be nice to see an option to replace the left-most page with something roughly equivalent or even completely different.

The more down to earth option:
Implement a simple list of news feeds powered by RSS, or perhaps research if any news aggregation services have freely-available APIs for use. The intended result is a drop in replacement for discover.

The less realistic, more challenging option:

Creating a specialized scrolling launcher page dedicated to widgets, akin to iOS. This would allow users to have faster access to their widgets + potentially customize their own Discover-like page.
(One issue that I realize about this proposal is that most launcher3-derived launchers aren't configured for vertical page scrolling and neither are most widgets, so stability and navigation may be challenging.)

**Comment by machiav3lli** [comment]
Actually we already have a plan to add such "shelf", but it's a long term addition. Am not sure if it'll come with v1, but it's already on my personal long todo-list.

**Comment by saulhdev** [comment]
It will be handle as a separated project @ https://github.com/saulhdev/OmegaFeeder
