### ISSUE TITLE
F-Droid repo not signed correctly

### ISSUE THREAD

**Issue by l3u** [NeoApplications/Neo-Launcher#210]
Hi :-)

When syncing F-Droid using your repo, I get (since a few days):

`Repository not signed correctly: Signing certificate does not match!`

Maybe, you want to investigate this.

Cheers, Tobias

**Comment by l3u** [comment]
Oh, it seems that the URL was changed or something. I re-added the repo linkes here, and now it works again. Sorry for the spam ;-)

**Comment by nonaybay** [comment]
[https://t.me/neo_fdroid/636](https://t.me/neo_fdroid/636)
