### ISSUE TITLE
[Feature Request] Add some useful search engines. 

### ISSUE THREAD

**Issue by extropista** [NeoApplications/Neo-Launcher#213]
I like the variety of search engines that the application has, however I think it would be useful if they added **private.sh** (GigaBlast.com) as it is more transparent (ethical) and functional than services like DuckDuckGo or I would even say more than BraveSearch for example.

 Another search engine that is not open-source, but deserves to be is **you.com** due to its great utility for searches related to code development or programming.

**Comment by machiav3lli** [comment]
duplicate of #112 , it's on the roadmap for v1
