### ISSUE TITLE
Vertical resizing isn't working on widgets.

### ISSUE THREAD

**Issue by fnldstntn** [NeoApplications/Neo-Launcher#217]
## Description
The widgets can't be resized vertically. 

## Steps to Reproduce
Try resizing a widget

## Device and OS
Device: Poco X3 Pro "vayu"
Android version: 12.1
Launcher version: 0.9.1
Rom: Arrow Os 12.1

![Screenshot_20220809-084316_Neo Launcher](https://user-images.githubusercontent.com/18335837/183588251-28369389-eb72-4eca-a7d8-41f771124ee6.png)

**Comment by machiav3lli** [comment]
The launcher respects the limits set by the widgets themselves. Note that most widgets don't set such limits, but if they do so, it may be for UX reasons

**Comment by fnldstntn** [comment]
İn that case, can it be added as a future?

**Comment by fnldstntn** [comment]
İt is not a bug.
