### ISSUE TITLE
App icons revert to default after app update (with workaround)

### ISSUE THREAD

**Issue by bedohave** [NeoApplications/Neo-Launcher#218]
## Description

Using ver 0.9.1, apps lose their icons after I update them (through Play store). 

## Expected Behavior

Upon update, Neo should continue to show the apps' icons.

## Actual Behavior

Upon update, Neo replaces the upgraded apps' icons with default android (white robot head on blue background).

## Steps to Reproduce

1. Update an app on Play store.
2. Return to Launcher. Updated apps will have system default (not their own) icons. These show in app drawer, too.
3. Unless you do the workaround, all updated apps keep this system default icon. As soon as you do the workaround for one app, all apps' icons get fixed. 

**Workaround**
1. Press and hold icon, select Customize.
2. Tap app icon (shows correctly) to edit the icon.
4. In the icon select screen, tap the smaller one to the right to (re-)select it.
5. Proper app icon appears for this *and all the other recently updated apps that had corrupted icons*. 

## Device and OS

* Device: Pixel 4a (also Lenovo Tab P11 Plus)
* Android version: 12 (11)
* Launcher version: 0.9.1 (same)
* Rom: ?? (??)

**Comment by saulhdev** [comment]
Fixed in commit 0fdd95124154dcb9955d9582fc06225cb969849f
