### ISSUE TITLE
Search bar drawer artifacts after killing / crashing app

### ISSUE THREAD

**Issue by mahdi1234** [NeoApplications/Neo-Launcher#222]
Having launcher set to Black (system theme) with search bar in app drawer looking like  this

![drawer_1](https://user-images.githubusercontent.com/1097047/183893129-90cb1c10-d803-45c9-bda1-5f1858947c5c.jpg)

1.  Swipe up to open drawer from desktop
2. Scroll down little bit so most-top apps are now "hidden" (won't manifest with default drawer app view)
3. Open any app
4. Using "kill back" back button to kill the app. Similar happens when app crashes or when closed normally with back button.

Observed:

Top part of drawer has now grayish artifacts.

![drawer_2](https://user-images.githubusercontent.com/1097047/183893522-df84a2c1-4a1b-4c3d-9f13-6e1216e5f7a4.jpg)

LOS 18.1 with Neo Launcher 0.9.1

**Comment by bobberb** [comment]
+1
