### ISSUE TITLE
Immediate consistent crash on Lenovo Tablet

### ISSUE THREAD

**Issue by doobydooby72** [NeoApplications/Neo-Launcher#226]
## Description

Crashes immediately no workaround

## Expected Behavior

That it should run for a while at least

## Actual Behavior

Crashes immediately

## Steps to Reproduce

1. Install
2. Run
3. Crash

## Device and OS

* Device: Lenovo TB-X605F
* Android version: 9.0
* Launcher version: 0.9.2
* Rom: Stock

❤️

**Comment by machiav3lli** [comment]
Crashlog?

**Comment by saulhdev** [comment]
fixed in #247
