### ISSUE TITLE
[Feature Request] add possibility to have other apps as "feed provider"

### ISSUE THREAD

**Issue by SacredPlaything** [NeoApplications/Neo-Launcher#227]
## Description
under feed providers, the only option is Google. Is it possible to add compatibility with other apps, for example Pocket by Mozilla, or an RSS reader app?

**Comment by saulhdev** [comment]
The current preference already supports different feed providers, you can try [HomeFeeder](https://github.com/iTaysonLab/HomeFeeder). 
Note that feed is not the same as RSS reader, a Feed can implements RSS reader, but the apps need to implements an Overlay Service to work with the current preference.
