### ISSUE TITLE
Unable to move apps into folder when inside app drawer

### ISSUE THREAD

**Issue by tsievert** [NeoApplications/Neo-Launcher#228]
## Description
At the moment, you seem to only be able to select apps for app drawer folders when inside the launcher settings. When you try to select apps from inside the app drawer, the changes are not saved.

## Expected Behavior
Open app drawer. Choose existing folder. 
Add additional apps.
Selection is saved.

## Actual Behavior
Selection is discarded

## Steps to Reproduce
1. Have folder with apps in app drawer
2. Open app drawer
3. tap folder
4. Open folder settings
5.  Select 'Manage apps'
6.  Select additional app(s)
7.  Use back gesture (Pixel)
8.  Changes are discarded

## Device and OS

Google Pixel 6A
Android version: 12.0.0
Launcher version: 0.9.1

**Comment by saulhdev** [comment]
Fixed on v0.9.3
