### ISSUE TITLE
[Feature Request] Option to change background color and opacity for folder background in dock

### ISSUE THREAD

**Issue by tsievert** [NeoApplications/Neo-Launcher#229]
At the moment the folder background color seems to follow the launcher theme, without any aoptio to change the colour or adjust the opacity.

Please make the (dock) folder background color customizable.

**Comment by kenwud** [comment]
I'd  like to second this feature

**Comment by enrico223** [comment]
As far as customization goes, this would be awesome

**Comment by saulhdev** [comment]
Added on v1.0
