### ISSUE TITLE
Really slow drawer search after turning on 'Find Hidden Shortcuts'

### ISSUE THREAD

**Issue by Parkourist** [NeoApplications/Neo-Launcher#230]
## Description

It takes 2-10 seconds to search for apps when u have 'Find Hidden Shortcuts' in Drawer Settings enabled.

## Expected Behavior

It should be a similar speed to normal search.

## Actual Behavior

A search for an app takes 2-10 seconds before it changes the results.

## Steps to Reproduce

1. Open Neo Launcher settings
2. Go to drawer settings
3. Enable 'Find Hidden Shortcuts' under Drawer search bar.
4. Open your drawer and search for an app.

https://imgur.com/a/kViH9u8 example

## Device and OS

* Device: Oneplus 6T
* Android version: 12
* Launcher version: 0.9.2 (according to izzyondroid)
* Rom: LineageOS Fajita 19.1

**Comment by saulhdev** [comment]
this issue is already fixed in commit ca47f045 and will be available in the next release.
