### ISSUE TITLE
Unable to switch directly to desktop after phone was locked on "Recents"

### ISSUE THREAD

**Issue by tsievert** [NeoApplications/Neo-Launcher#240]
## Description
If phone was locked on the "Recents" screen, you cannot tap empty space to return to desktop right away. You have to select an app and then return to desktop.

## Expected Behavior
1. Open "Recents"
2. Lock phone
3. Unlock phone. Still on "recents"
4. Tap emtpy space
5. Return to desktop

## Actual Behavior
Empty space is unresponsive.
You have to select first any app and return to desktop from there

## Steps to Reproduce
1. Open "Recents"
2. Lock phone
3. Unlock phone. Still on "recents"
4. Tap emtpy space
5. Phone is unresponsive to those taps.
6. Tap app instead.
7. App opens
8. Return to desktop

## Device and OS
* Device: Pixel 6a
* Android version: 13
* Launcher version: 0.9.2
* Rom: Stock Pixel

**Comment by machiav3lli** [comment]
Recents (quickstep) is managed by the system's launcher or your chosen recents provider using a magisk module.

This would cause the same incompatibilities with your other launchers too (e.g. LawnChair).

**Comment by tsievert** [comment]
Ah, so unfortunately a Pixel Launcher "feature".
Thanks!
