### ISSUE TITLE
[Bug] When any app gets updated, its icon is replaced by the generic Android icon

### ISSUE THREAD

**Issue by yattoz** [NeoApplications/Neo-Launcher#242]
## Description

When an app has an update, be it from the Google Play Store or from manual update (for example for F-Droid), the icon of the app is replaced by the generic Android icon (the droid face with checkered background). 

Note: here are the settings I used in the launcher settings.
- custom icon shape "Cupertino"
- Coloured background: ON
- Create adaptative icons from icon pack: ON

Since I have to wait for Google Play to push an update, it's quite inconvenient to test, and I am not sure where the problem comes from (maybe only Cupertino? maybe all icon shapes? maybe even system shape?). Maybe there could be a simpler way to reproduce the bug?

## Expected Behavior

I would expect that the app keeps its icon if it hasn't changed, or is updated to a new icon if the update provides a new icon.

## Actual Behavior

Currently, the icon displayed is the generic Android icon.

## Steps to Reproduce

1. Wait for an application to update
2. See the icon

Here is a workaround to make the icon re-appear:

1. Open Neo-launcher settings
2. Go to Theme -> Customize Icons
3. Select any icon shape. This seems to reinitialize the icons somehow.

## Device and OS

* Device: Google Pixel 5a (5G) (Japanese version)
* Android version: Android 13, build number TP1A.220624.014
* Launcher version: 0.9.2 build 926 (from IzzyOnDroid)
* Rom: Stock rom.

**Comment by saulhdev** [comment]
already fixed
