### ISSUE TITLE
[Feature Request] Other weather providers

### ISSUE THREAD

**Issue by Akselmo** [NeoApplications/Neo-Launcher#246]
I don't have Google app in my phone (I use /e/os) but I'd like to see the weather in the smart space/widget. 

Having something like OpenWeatherMap as another weather source would be nice. Users could supply
their own API there.

There are also alternatives like Yahoo weather and such.

Thanks for the great launcher. :)

**Comment by machiav3lli** [comment]
OWM has being added lately and would come with long-waited 0.9.3. Other providers may come too.
