### ISSUE TITLE
[Feature Suggestion] Theme Icons and Material You

### ISSUE THREAD

**Issue by Relms12345** [NeoApplications/Neo-Launcher#248]
Hey! Are there any plans to add support for Theme Icons like lawnicons (and it's derivatives) and Material You support? I hope they can be implemented as it's the only 2 features holding me back from switching from Lawnchair.

Edit: I could attempt to PR it if needed though I'm not too familiar with Kotlin

**Comment by machiav3lli** [comment]
They may come in the future, when we rebase to A13.

**Comment by Relms12345** [comment]
Sounds good thanks!

**Comment by machiav3lli** [comment]
Let's keep it open, as this may help to avoid that others create duplicates.

**Comment by 2br-2b** [comment]
I'm looking forward to when this feature gets added! The launcher is already amazing, but this would be a welcome addition to the app.

**Comment by endim8** [comment]
+1 for Monet support!

**Comment by saulhdev** [comment]
Added on v0.9.3
