### ISSUE TITLE
[BUG] App Icons dissapear after the app is updated

### ISSUE THREAD

**Issue by the16bitgamer** [NeoApplications/Neo-Launcher#251]
After an app is updated from Google Play or F-Droid, the icon changes to the Default Android app icon, and only refreshes when you change the icon style.

## Description
Noticed this since the latest update, when an app updates at times the app icon disappears and a blank android icon appears in it's place. The icons remain the default even after a restart and will only change when I change the icons theme i.e. enabling/disabling the "Create adaptive icons for icon pack" or "Colored backgrounds"

## Expected Behavior
When an app updated the new icon is included as well

## Actual Behavior
App icon is removed and the default android app icon is shown

## Steps to Reproduce

1. Update an app from Google Play or F-Droid
2. Find app in the launcher or app drawer

## Device and OS
Device: Poco X3 Pro: Vayu
Android version: 11
Launcher version: 0.9.2
Rom: Arrow-v11.0-vayu-OFFICIAL-20220303-VANILLA

**Comment by saulhdev** [comment]
Duplicated of #243
