### ISSUE TITLE
Uninstall with long press on the app

### ISSUE THREAD

**Issue by Donnnno** [NeoApplications/Neo-Launcher#256]
Right now there are two options when you long press on an icon. It would be great to have an _uninstall app_ option besides the _info_ and _edit_ functions.

Thanks for the great launcher!

**Comment by Ghostfreak803** [comment]
If you're talking about icons in app drawer, the 'uninstall' option can be added in the "Drawer" settings.

It's in the "Shortcut Bubble" option:

![IMG_20220927_221204_129](https://user-images.githubusercontent.com/35540132/192586047-00a30501-73f1-4a63-a13d-94b902651469.jpg)
![Screenshot_20220927-221425_Neo Launcher](https://user-images.githubusercontent.com/35540132/192586446-737badd9-7d04-4a66-9dd5-f8271dffe3c9.jpg)

**Comment by Donnnno** [comment]
Thanks! 

I overlooked this one, oops
