### ISSUE TITLE
Search bar does not fill the width of the screen

### ISSUE THREAD

**Issue by LilithhhBlackkk** [NeoApplications/Neo-Launcher#257]
## Description
![Screenshot_20220925-165435_Neo Launcher](https://user-images.githubusercontent.com/98243609/192141116-2592cda5-e05a-4bcf-be0d-c76b78974f85.jpg)

## Expected Behavior
The search bar should fill the width of the screen

## Actual Behavior
It seems to fill approximately a third

## Steps to Reproduce

1. Set the screen size to small
2. Open the search 

## Device and OS
* Device: Samsung Galaxy s20fe -->
* Android 12
* Launcher version: 0.9.3 alpha 1

**Comment by saulhdev** [comment]
Fixed on v1.0
