### ISSUE TITLE
Crash if changing icon pack without storage permission

### ISSUE THREAD

**Issue by GithubUser699** [NeoApplications/Neo-Launcher#258]
## Description
Settings crashes and doesn't display a popup asking for necessary permission(s).

## Expected Behavior
Shouldn't crash, should display popup asking for necessary permission(s).

## Actual Behavior
Crashes, does not display popup asking for necessary permission(s).

## Steps to Reproduce

1. Go to "Home Settings"
2. Go to "Theme"
3. Press "Icon Packs"
4. It crashes

## Device and OS

Device: Xiaomi Mi A2 (jasmine_sprout)
Android version: 11
Launcher version: 0.9.2 (Build 926)
Rom: LineageOS 18.1

## Logcat

> 09-27 23:59:48.480 30448 30448 D AndroidRuntime: Shutting down VM
09-27 23:59:48.481 30448 30448 E AndroidRuntime: FATAL EXCEPTION: main
09-27 23:59:48.481 30448 30448 E AndroidRuntime: Process: com.saggitt.omega, PID: 30448
09-27 23:59:48.481 30448 30448 E AndroidRuntime: android.view.InflateException: Binary XML file line #25 in com.saggitt.omega:layout/fragment_icon_pack: Binary XML file line #25 in com.saggitt.omega:layout/fragment_icon_pack: Error inflating class com.saggitt.omega.iconpack.IconPackPreview
09-27 23:59:48.481 30448 30448 E AndroidRuntime: Caused by: android.view.InflateException: Binary XML file line #25 in com.saggitt.omega:layout/fragment_icon_pack: Error inflating class com.saggitt.omega.iconpack.IconPackPreview
09-27 23:59:48.481 30448 30448 E AndroidRuntime: Caused by: java.lang.reflect.InvocationTargetException
09-27 23:59:48.481 30448 30448 E AndroidRuntime: 	at java.lang.reflect.Constructor.newInstance0(Native Method)
09-27 23:59:48.481 30448 30448 E AndroidRuntime: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
09-27 23:59:48.481 30448 30448 E AndroidRuntime: 	at android.view.LayoutInflater.createView(LayoutInflater.java:852)
09-27 23:59:48.481 30448 30448 E AndroidRuntime: 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1004)
09-27 23:59:48.481 30448 30448 E AndroidRuntime: 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:959)
09-27 23:59:48.481 30448 30448 E AndroidRuntime: 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1121)
09-27 23:59:48.481 30448 30448 E AndroidRuntime: 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1082)
09-27 23:59:48.481 30448 30448 E AndroidRuntime: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:680)
09-27 23:59:48.481 30448 30448 E AndroidRuntime: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:532)
09-27 23:59:48.481 30448 30448 E AndroidRuntime: 	at com.android.launcher3.databinding.FragmentIconPackBinding.inflate(FragmentIconPackBinding.java:56)
09-27 23:59:48.481 30448 30448 E AndroidRuntime: 	at com.saggitt.omega.preferences.views.IconPackFragment.onCreateView(IconPackFragment.kt:69)
09-27 23:59:48.481 30448 30448 E AndroidRuntime: 	at androidx.fragment.app.Fragment.performCreateView(Fragment.java:3104)
09-27 23:59:48.481 30448 30448 E AndroidRuntime: 	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:524)
09-27 23:59:48.481 30448 30448 E AndroidRuntime: 	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
09-27 23:59:48.481 30448 30448 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1890)
09-27 23:59:48.481 30448 30448 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1808)
09-27 23:59:48.481 30448 30448 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1751)
09-27 23:59:48.481 30448 30448 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:538)
09-27 23:59:48.481 30448 30448 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
09-27 23:59:48.481 30448 30448 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
09-27 23:59:48.481 30448 30448 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:223)
09-27 23:59:48.481 30448 30448 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7664)
09-27 23:59:48.481 30448 30448 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
09-27 23:59:48.481 30448 30448 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
09-27 23:59:48.481 30448 30448 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
09-27 23:59:48.481 30448 30448 E AndroidRuntime: Caused by: java.lang.SecurityException: Permission android.permission.READ_EXTERNAL_STORAGE denied for package com.saggitt.omega
09-27 23:59:48.481 30448 30448 E AndroidRuntime: 	at android.os.Parcel.createExceptionOrNull(Parcel.java:2373)
09-27 23:59:48.481 30448 30448 E AndroidRuntime: 	at android.os.Parcel.createException(Parcel.java:2357)
09-27 23:59:48.481 30448 30448 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:2340)
09-27 23:59:48.481 30448 30448 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:2282)
09-27 23:59:48.481 30448 30448 E AndroidRuntime: 	at android.app.IWallpaperManager$Stub$Proxy.getWallpaperWithFeature(IWallpaperManager.java:883)
09-27 23:59:48.481 30448 30448 E AndroidRuntime: 	at android.app.WallpaperManager$Globals.getCurrentWallpaperLocked(WallpaperManager.java:487)
09-27 23:59:48.481 30448 30448 E AndroidRuntime: 	at android.app.WallpaperManager$Globals.peekWallpaperBitmap(WallpaperManager.java:439)
09-27 23:59:48.481 30448 30448 E AndroidRuntime: 	at android.app.WallpaperManager$Globals.peekWallpaperBitmap(WallpaperManager.java:415)
09-27 23:59:48.481 30448 30448 E AndroidRuntime: 	at android.app.WallpaperManager.getDrawable(WallpaperManager.java:609)
09-27 23:59:48.481 30448 30448 E AndroidRuntime: 	at com.saggitt.omega.wallpaper.WallpaperPreviewProvider.loadWallpaper(WallpaperPreviewProvider.kt:67)
09-27 23:59:48.481 30448 30448 E AndroidRuntime: 	at com.saggitt.omega.wallpaper.WallpaperPreviewProvider.getWallpaper(WallpaperPreviewProvider.kt:55)
09-27 23:59:48.481 30448 30448 E AndroidRuntime: 	at com.saggitt.omega.iconpack.IconPackPreview.<init>(IconPackPreview.kt:60)
09-27 23:59:48.481 30448 30448 E AndroidRuntime: 	at com.saggitt.omega.iconpack.IconPackPreview.<init>(IconPackPreview.kt:41)
09-27 23:59:48.481 30448 30448 E AndroidRuntime: 	at com.saggitt.omega.iconpack.IconPackPreview.<init>(Unknown Source:11)
09-27 23:59:48.481 30448 30448 E AndroidRuntime: 	... 25 more
09-27 23:59:48.481 30448 30448 E AndroidRuntime: Caused by: android.os.RemoteException: Remote stack trace:
09-27 23:59:48.481 30448 30448 E AndroidRuntime: 	at android.os.storage.StorageManager.checkPermissionAndAppOp(StorageManager.java:1776)
09-27 23:59:48.481 30448 30448 E AndroidRuntime: 	at android.os.storage.StorageManager.checkPermissionAndAppOp(StorageManager.java:1753)
09-27 23:59:48.481 30448 30448 E AndroidRuntime: 	at android.os.storage.StorageManager.checkPermissionAndAppOp(StorageManager.java:1820)
09-27 23:59:48.481 30448 30448 E AndroidRuntime: 	at android.os.storage.StorageManager.checkExternalStoragePermissionAndAppOp(StorageManager.java:1936)
09-27 23:59:48.481 30448 30448 E AndroidRuntime: 	at android.os.storage.StorageManager.checkPermissionReadImages(StorageManager.java:1902)
09-27 23:59:48.481 30448 30448 E AndroidRuntime: 
09-27 23:59:48.485  1560  4331 W ActivityTaskManager:   Not force finishing home activity com.saggitt.omega/.OmegaLauncher
09-27 23:59:48.485  1560  4331 W ActivityTaskManager:   Force finishing activity com.saggitt.omega/.preferences.views.PreferencesActivity
09-27 23:59:48.485  1560 30691 I DropBoxManagerService: add tag=data_app_crash isTagEnabled=true flags=0x2
09-27 23:59:48.495  1560  4331 I ActivityTaskManager: Clearing package preferred activities from com.saggitt.omega
09-27 23:59:48.497 30448 30448 I Process : Sending signal. PID: 30448 SIG: 9
09-27 23:59:48.544  1560  2135 I WindowManager: WIN DEATH: Window{159cd8a u0 com.saggitt.omega/com.saggitt.omega.preferences.views.PreferencesActivity}
09-27 23:59:48.544  1560  2135 W InputDispatcher: Attempted to unregister already unregistered input channel '159cd8a com.saggitt.omega/com.saggitt.omega.preferences.views.PreferencesActivity (server)'
09-27 23:59:48.545   709   709 I Zygote  : Process 30448 exited due to signal 9 (Killed)
09-27 23:59:48.546  1560  8218 I ActivityManager: Process com.saggitt.omega (pid 30448) has died: fg  TOP 
09-27 23:59:48.547  1560  1839 I libprocessgroup: Successfully killed process cgroup uid 10359 pid 30448 in 0ms

Especially note 

> 09-27 23:59:48.481 30448 30448 E AndroidRuntime: Caused by: java.lang.SecurityException: Permission android.permission.READ_EXTERNAL_STORAGE denied for package com.saggitt.omega

After I granted storage access ("Allow access to media only") the icon packs setting works just fine.

**Comment by saulhdev** [comment]
Fixed on v0.9.3
