### ISSUE TITLE
App overview -  sort apps that contain umlauts

### ISSUE THREAD

**Issue by Tianonymus** [NeoApplications/Neo-Launcher#260]
## Description
In the app overview we can sort apps alphabetically. However with regard to German umlauts (Ä, Ö, Ü) this is not handled correctly. It was in previous versions (Omega) of the launcher if I'm not totally mistaken.

## Behavior
Usually these letters are grouped with their respective base letter A, O, U. 

A very common way is to treat them the same, so Ä as an A etc. There's even a norm for this, of course there is, we're German lol. DIN 5007

I see this with the app Öffi. I'd expect it to be between Octodroid and Open Camera. Instead it's listed at the very end of the app list.

## Steps to Reproduce
Install an app with an umlaut in it's name and see where it's listed.

https://f-droid.org/packages/de.schildbach.oeffi/

## Device and OS
* Device: Nokia G21
* Android version: 11
* Launcher version: 0.9.2 via F-Droid

Would be really nice if you could fix this, but obviously it's no big priority. I assume it's just a matter of implementating how to sort correctly according to the set language.

Thanks a lot for the awesome launcher and everybody's work on it!

**Comment by saulhdev** [comment]
Maybe you can help me with this @machiav3lli

**Comment by machiav3lli** [comment]
And voila! Done.
