### ISSUE TITLE
[Bug] Settings don't work on Motorola G Pure (OEM's A11)

### ISSUE THREAD

**Issue by JaydenDev** [NeoApplications/Neo-Launcher#264]
My issue, the fact that *nothing* works. Using and installing the latest release, the first thing I tried to do was change some settings. I first went to the layout, trying to change from 5x5 to 6x5. When I clicked OK.. nothing happened. Nothing in settings reflected my change, neither did the home screen. Then I tried to figure out why it hadn't switched to dark mode (the system theme), it's set to system, why isn't it changing? Not a great start, customization doesn't work. Though without trying to change settings it *sort* of works. In general, I wouldn't expect the *settings* to be the failing component here. My expected behavior is that all changes in settings listed, actually make a difference. Hope this launcher gets fixed!
## Steps to Reproduce
1. Change *any* setting
2. See it not work
## Device and OS
Device: Moto G Pure (2021)
Android Release: 11.0 (Security Patch: August 2022, Google Play System Update: August 2022)
Launcher Version: v0.9.2
ROM: Stock Android System (11.0) Motorola OEM Software

**Comment by machiav3lli** [comment]
"Nothing works" doesn't help and isn't the "normal" state, so there might be something "unique" about your setup, that results the mentioned issues.

Maybe you can be constructive and list two or three step for step examples of what doesn't work

**Comment by JaydenDev** [comment]
> "Nothing works" doesn't help and isn't the "normal" state, so there might be something "unique" about your setup, that results the mentioned issues.
> 
> Maybe you can be constructive and list two or three step for step examples of what doesn't work

The examples of what don't work is *in* the OP.
