### ISSUE TITLE
Hidden apps search fail

### ISSUE THREAD

**Issue by appbap** [NeoApplications/Neo-Launcher#268]
## Description
If I have over 8 apps hidden, I cannot search for certain apps even with the "Find Hidden Shortcuts" option selected. I am using folders in the app drawer. 

## Steps to Reproduce
 Hide over 8 apps in the drawer, have "Find Hidden Shortcuts" option on, try to search for hidden apps. It seems some show, but not others.

## Device and OS
Pixel 7

**Comment by appbap** [comment]
Update: Two hidden apps (Bitwarden, and Signal) are not able to be searched for with the above settings, while other hidden apps are.

**Comment by saulhdev** [comment]
what version of the launcher?
Is the fuzzy search enabled?

**Comment by appbap** [comment]
> what version of the launcher? Is the fuzzy search enabled?

Version 0.9.2 (Build 926)

I tried fuzzy search, still no luck.

**Comment by saulhdev** [comment]
search hidden apps works very slow on v0.9.2. I would recomend keep it disbled until v0.9.3 is released
