### ISSUE TITLE
[BUG] THEMED ICONS FROM LAWNICONS NOT WORKING.

### ISSUE THREAD

**Issue by SkyDevstronger** [NeoApplications/Neo-Launcher#280]
![Screenshot_20221107-133217.png](https://user-images.githubusercontent.com/97104388/200388024-caf1365e-dc68-45e5-ba75-e0eb3bf0ccf6.png)

**Comment by saulhdev** [comment]
what is your OS version and flavor?

**Comment by SkyDevstronger** [comment]
A9 pure

**Comment by saulhdev** [comment]
The themed icons work on Android 12+ only. So the issue here is that the Lawnicons shouldn't be visible on the icon preference is your version is lower than 12.
