### ISSUE TITLE
Icons disappear when an app is updated

### ISSUE THREAD

**Issue by ayesc9000** [NeoApplications/Neo-Launcher#281]
On version 0.9.3, icons may disappear when an app has been updated.

Running Android 13 beta
Using F-Droid build

**Comment by ayesc9000** [comment]
Ok so it seems to not be occurring at random. It seems that it may occur after an app has been updated.

**Comment by quite** [comment]
I have what I think is the same issue on an Android 12 device. When an app is updated, the icons do not *disappear*, but it becomes that "default development icon" -- white android head on blue/white grid.

To work around the issue (until it happens again) I can long-tap the icon, tap "Customize", tap the icon, and pick the correct icon. This sometimes also corrects other bad icons that are present at this time.

**Comment by eleius** [comment]
> On version 0.9.3, icons may disappear when an app has been updated.
> 
> Running Android 13 beta Using F-Droid build

Same here on my Android 11 device. Icons also disappear when a new icon has been added (e.g. apps installed via adb install). I don't know if it's relevant but I'm using a custom grid size of 5x5.

Anyway I love this launcher, thanks for your work!

**Comment by jbigot** [comment]
Same with neo launcher 0.9.2 on Android 13

**Comment by ayesc9000** [comment]
**Friendly notice:**
I can no longer recreate this specific case if any devs need it, as I got a new phone a few months back. I also haven't been using Neo Launcher since early 2023 due to the complete lack of updates. I will leave this issue open, though, as it still seems to be occurring for other people.

**Comment by jbigot** [comment]
still occurs to me indeed

**Comment by saulhdev** [comment]
Fixed on v1.0
