### ISSUE TITLE
[Feature Request] custom Accent Color

### ISSUE THREAD

**Issue by snoweuph** [NeoApplications/Neo-Launcher#282]
Currently you can Only choose your Accent Color from a Big list. I want to be able to choose specific colors myself. I personally use a specific color scheme for my system as far as I can.
![Screenshot_20221111-113713_Neo Launcher.png](https://user-images.githubusercontent.com/76737863/201322931-72ba9142-2205-4249-b37b-e03b8b2f19ab.png)

Also allow to set the base Dark and Light color tha that are set through the Theme Option

![Screenshot_20221111-113729_Neo Launcher.png](https://user-images.githubusercontent.com/76737863/201322987-c074c10b-5f2d-4a18-b1f4-c17a063c14c8.png)

**Comment by saulhdev** [comment]
Added on v1.0
