### ISSUE TITLE
Fastlane: TR full_descriptions need formatting

### ISSUE THREAD

**Issue by IzzySoft** [NeoApplications/Neo-Launcher#303]
I just noticed that  the Turkish `full_description.txt` files are not rendering properly due to missing line breaks – i.e. it lacks an empty line before and after the bullet-pont list, turning the entire description into a single paragraph. I've fixed that manually in my repo for now, but you might wish to correct that here, too (else it would overwrite my corrections one day).

**Comment by saulhdev** [comment]
Fixed in commit 1f32146

**Comment by IzzySoft** [comment]
Thanks!
