### ISSUE TITLE
Adaptive icons background is always colored

### ISSUE THREAD

**Issue by lfom** [NeoApplications/Neo-Launcher#317]
## Description
Settings > Profile > Icon shape > Colored backgrounds toggle does not seem to work, either if it is on or off the adaptive icons is always colored. In my opinion, the background color is too dark, with low contrast to the icon itself, so I think this option would make the background white but it does seem to change anything at all.

## Expected Behavior
Disabling "Coloured backgrounds" makes the background of adaptive icons white.

## Actual Behavior
Adaptive icons background is always some (dark) color, regardless of the toggle "Coloured backgrounds" being on or off.

## Steps to Reproduce

1. Open Neo-Launcher settings
2. Go to Profile > Icon shape 
3. Change the option "Coloured backgrounds"
4. (Optional) restart the launcher to make sure the new change was applied

## Device and OS

* Device: moto g(8)
* Android version: 11
* Launcher version: 0.9.3 (934)
* Rom: Havoc-OS

## Logcat

N/A

**Comment by saulhdev** [comment]
Fixed on the current v1.0

**Comment by lfom** [comment]
> Fixed on the current v1.0

Thank you! Hopefully new versions of the Neo apps will be released soon, the last one was in 2022. :blush:
