### ISSUE TITLE
[Feature] Pick accent color from wallpaper

### ISSUE THREAD

**Issue by lfom** [NeoApplications/Neo-Launcher#318]
## Description
Neo-Launcher can pick the theme from wallpaper in Settings > Profile > Theme, it would be really nice if it could also pick the Accent Color from the wallpaper too.

## Expected Behavior
Neo-Launcher is able to pick the Accent Color from the current wallpaper, and updates it automatically if the wallpaper is changed if the option is enabled.

## Actual Behavior
N/A

## Steps to Reproduce

N/A

## Device and OS

* Device: moto g(8)
* Android version: 11
* Launcher version: 0.9.3 (934)
* Rom: Havoc-OS

## Logcat

N/A

**Comment by goyalyashpal** [comment]
this will make it like the Android12 Material You's adaptive system colors, nice :)

**Comment by saulhdev** [comment]
Already implemented in the current development version.
