### ISSUE TITLE
Cannot add some app to the sidebar for quick access

### ISSUE THREAD

**Issue by notYetLost** [NeoApplications/Neo-Launcher#321]
## Description

Sliding in from the left edge, then press: opens the quick access sidebar (what term is officially used for this feature?).

When I try to add some specific app (TWINT app for immediate payments to Swiss banks provided by Raiffeisenbank), I cannot find it.
I do find other apps to choose from the same bank.

Why are some apps not listed to be added to the sidebar?

## Expected Behavior

I can find any app installed by myself to add to the sidebar.

## Actual Behavior

Sliding in from the left edge, then press: opens the quick access sidebar.

When I try to add some specific app (TWINT app for immediate payments to Swiss banks provided by Raiffeisenbank), I cannot find it.
I do find other apps to choose from the same bank.

## Steps to Reproduce

1. Sliding in from the left edge, then press: opens the quick access sidebar (what term is officially used for this feature?).
2.Press the "four square" icon on the bottom of the sidebar
3.On the right pane search for the app to be added
4.result: "Raiffeisen TWINT" app cannot be found; this app is for immediate payments to Swiss banks provided by Raiffeisenbank to its customers

## Device and OS

* Device:  Huawei Mate 20 X "EVR-L29"
* Android version:  Android 10
* Launcher version:  EMUI 12.0.0.132
* Rom:  C432E4R1P2patch

**Comment by saulhdev** [comment]
The quick sidebar is a EMUI feature, if any app is not available to add it, it depends of the EMUI itself and not of Neo Launcher.
