### ISSUE TITLE
Cannot change tab color

### ISSUE THREAD

**Issue by Elbullazul** [NeoApplications/Neo-Launcher#332]
The app won't change a tab's color when using the tab long-press menu or via the launcher's settings

## Expected Behavior
When changing a tab's color, the new color should be immediately applied

## Actual Behavior
Long-pressing a tab and pressing "tab color" returns me to the home screen

When trying to change a tab's color via launcher settings (drawer > categorize > select a tab > tab color), the new color will not be applied, and the launcher will revert to the old color

## Steps to Reproduce
Long-press tab in drawer, press "Tab color"
Alternatively, change color in launcher settings

## Device and OS
* Device: Pixel 6 Pro
* Android version: 13
* Launcher version: 0.9.3
* Rom: Calyx OS 4.6.0

**Comment by Elbullazul** [comment]
Perhaps related to [this issue](https://github.com/NeoApplications/Neo-Launcher/issues/53)?

**Comment by saulhdev** [comment]
Fixed 0beb8cc8
