### ISSUE TITLE
How to set Neo Launcher as the default launcher

### ISSUE THREAD

**Issue by xvzhenduo** [NeoApplications/Neo-Launcher#334]
How to set Neo Launcher as the default launcher

## Description
I can't find it in the default launcher setting.(see the picture below)
![image](https://user-images.githubusercontent.com/74353173/222874687-b96c00cb-2c77-412c-ae9e-c2d1098e45ce.png)
When I try to use adb to set it as the default launcher(using `adb shell pm set-home-activity "com.saggitt.omega/.OmegaLauncher"`)
```
java.lang.IllegalArgumentException: Component ComponentInfo{com.saggitt.omega/com.saggitt.omega.OmegaLauncher} not allowed to be home on user 0
```

## Device and OS

* Device: HUAWEI Mate 9 (MHA-AL00)
* Android version: 9
* Launcher version: 0.9.3
* Rom: EMUI 9.0.1

**Comment by machiav3lli** [comment]
As far as I recall Huawei doesn't allow users to set different launcher as default, specially on its devices for the chinese market.
