### ISSUE TITLE
[**Feature(a must need?)] 2click needed instead of one

### ISSUE THREAD

**Issue by Tanzin01** [NeoApplications/Neo-Launcher#338]
![Screenshot_20230323-211621](https://user-images.githubusercontent.com/41266558/227249387-309df5aa-fd96-4889-b2bb-0116eaf5765e.png)

not sure what its called where i can group multiple app like the above photo.  Finding and requiring 2 clicks is not so good to run a app.

So how about making those apps clickable inside that group drawer thing? i.e if i can right above corrner of that drawer, the right above corner app opens. This will reduce clicks

**Comment by machiav3lli** [comment]
Sorry, but can you explain yourself better…
Neo Launcher includes many ways to group apps. Here's some:
- Folder cover mode: Swipe up gesture
- Drawer groups: Folders
- Drawer groups: Tabs

**Comment by Tanzin01** [comment]
My bad. I got things to learn. Anyway, what i mean is-

![Screenshot_20230325-132916](https://user-images.githubusercontent.com/41266558/227703793-7c94b431-acc1-4793-9353-519aebeb0732.png)
1) Thats my screen. I wanna open "fdroid" from that drawer.

![Screenshot_20230325-132925](https://user-images.githubusercontent.com/41266558/227703850-d608fb5c-51e7-43ad-bdc3-30ef2627fe5a.png)
2) i clicked that drawer and it expanded. [1st click]
3) now i click fdroid for it to open.[total 2 clicks required to open.]

This is what i meant.

or, another way to open is, touch twice on the icon of "fdroid" for it to open from 1st pic screen.

**Comment by Tanzin01** [comment]
Im suggesting "click reduction"

**Comment by machiav3lli** [comment]
How this "click reduction" would look like?
And as already mentioned there's already "cover mode" which makes first app of a folder accessible with one click while opening the folder through a swipe up.

**Comment by Tanzin01** [comment]
how would this look like: Did not give enough thought but from use perspective, 
![Screenshot_20230325-132916](https://user-images.githubusercontent.com/41266558/227734013-eecd6792-ace3-4242-bec1-08b71d7ad46b.png)
from the above picture, is it possible to make those icons clickable?

those 4 apps are inside a circle shape. lets imagine another circle inside this circle.  in-between the gap of these circles can be used  as app clickable area. and the inside of the smaller circle area can be used as a clickable location for expanding the drawer.

[did not thought yet about a drwaer with apps beyind 4]

**Comment by machiav3lli** [comment]
If you can work with such miniture icons and the space between (good for you), then you can simply double the number of columns and rows of the desktop (desktop grid size).

I can't imagine this being usable on "normal-sized" devices. Plus there's even more questions considering folders with more than 4 apps and further variables.

Furthermore, as already mentioned cover mode should provide a way to open the most important app with one tap, while the others would need only an extra swipe-up.
