### ISSUE TITLE
Neo-Laumcher crashes on startup on Calyx 4.7.5

### ISSUE THREAD

**Issue by jonathan-realman** [NeoApplications/Neo-Launcher#340]
## Description
App Crashes on most recent version of CalyxOS

## Expected Behavior
App opens normally on CalyxOS

## Steps to Reproduce
1. Start app
2. Crash

I assume it has to do with some compatibly calyx dropped

## Device and OS
Device: Pixel 4 
Android version: 13.0
Launcher version: 0.9.3
Rom: Calyx  4.7.5

**Comment by machiav3lli** [comment]
Crashlog?

I use it on the same mentioned version and works fully fine. Maybe some permissions were blocked after your update (I didn't face this, but maybe it's otherwise on your side).

**Comment by jonathan-realman** [comment]
> Crashlog?
> 
> I use it on the same mentioned version and works fully fine. Maybe some permissions were blocked after your update (I didn't face this, but maybe it's otherwise on your side).

Didn't have logcat installed so I will have to wait till I get home to enable it with adb.

**Comment by jonathan-realman** [comment]
> You can use Scoop, it's easier and provides only the crash log: https://www.f-droid.org/en/packages/taco.scoop/

It turns out the issue wasn't Calyx it was a KWGT widget, I emptied the storage (reset settings and cache) and it worked, had to recreate my custom designe but it's running again. Thanks a lot though.
