### ISSUE TITLE
Upgrade from Omega Launcher v0.8.1

### ISSUE THREAD

**Issue by stephen-hill** [NeoApplications/Neo-Launcher#342]
Hello

I am trying to upgrade to Neo Launcher from Omega Launcher (com.saggitt.omega).

Why trying to install via github apk I just get an "Install failed" error. When trying to update via F-Droid, it tells me that I have to remove the current version and that I will loose all settings.

What is the best way for me to upgrade and keep all my settings?

Many Thanks
Stephen

**Comment by machiav3lli** [comment]
There's no way to move without clearing data, 0.8.1 was still based on Android11, 0.9.X is based on Android12 and the upcoming 1.0.0 is based on Android13.
We're working on a way to support moving data forwards, but this would never come to older versions.
There's no ETA for 1.0.0.
