### ISSUE TITLE
Floating Icon can not be removed

### ISSUE THREAD

**Issue by myxor** [NeoApplications/Neo-Launcher#347]
## Description

There is a floating Icon of the launcher which can be moved on the left and right side and is always visible.
I can not remove it.

## Expected Behavior

No idea where it comes from. Would like to remove it.

## Actual Behavior

Icon is there permanently. It can not be removed but moved from left to right side (and back).
When clicking the Icon nothing happens. 

## Steps to Reproduce

1. I have no idea
2.
3.
4.

## Device and OS

* Device: Nexus 6a
* Android version: 13
* Launcher version: 0.9.3
* Rom: CalyxOS

## Logcat

```
your log here
```

## Screenshot (Icon on the left):

![Screenshot_20230510-024347](https://github.com/NeoApplications/Neo-Launcher/assets/1397377/b3493c72-64a2-4568-a5e6-2d7236414351)

**Comment by machiav3lli** [comment]
That's an accessibility shortcut, enabled by you. Just go to system settings → accessibility → Neo Launcher → then disable showing the shortcut (not the service as a whole).
