### ISSUE TITLE
Using bigger a bit bigger font sizes makes text close to unusable

### ISSUE THREAD

**Issue by alexanderadam** [NeoApplications/Neo-Launcher#351]
## Description

People with impaired vision might want to use bigger font sizes but right now this makes it hard to use

### Text is cut off

![Screenshot_20230527-104233_Neo Launcher](https://github.com/NeoApplications/Neo-Launcher/assets/372620/3bb54316-b52e-4121-bae0-e1fafd4457f0)

### And here it is not breaking into the next line

![Screenshot_20230527-103952_Neo Launcher](https://github.com/NeoApplications/Neo-Launcher/assets/372620/6906515b-502d-419d-bc8e-6bfa0bb7812a)

## Expected Behaviour

Everything is properly readable

## Actual Behaviour

In search just a few characters are visible before ellipsis and the start page will break successfully but cuts of text below.

## Steps to Reproduce

1. use bigger font sizes

**PS:** It's also relevant for others (i.e. [here](https://forum.xda-developers.com/t/how-can-i-set-the-lineageos-global-font-size.4427007/))

**Comment by saulhdev** [comment]
when you are using a bigger font size, you should reduce the column count so the text can have more gap to display the name.
I would suggest 4 columns instead of 5.
