### ISSUE TITLE
[Feature Request] Folder features

### ISSUE THREAD

**Issue by xenopiece99** [NeoApplications/Neo-Launcher#354]
Is there any possibility to implement these :
->Put folder(s) inside a folder
->Create folder in the app drawer 
         ->be able to make a shortcut of this folder in the home screen.
         ->When I put apps in these folders they are also updated in the shortcut in the home screen.
->put icons for the folders 
I know these are a lot of features for a folder but No launcher other than nova have these and are the only things keeping me from moving to Neo-Launcher which I really like.

**Comment by saulhdev** [comment]
Some features are already present, some other are not planed to be implemented. For example "put folder inside a folder".
