### ISSUE TITLE
crashes + no widgets on restore

### ISSUE THREAD

**Issue by pleadeis** [NeoApplications/Neo-Launcher#362]
## Description

I see this has been reported before but not sure if it was considered fixed. Also not sure if cause is the same.

## Expected Behavior

Work without crashing. 

Widgets restore with backup.

## Actual Behavior

Neolauncher crashes or resets itself. 

Backups do not restore widgets.

## Steps to Reproduce

I cannot reproduce. It has happened a bunch of times.It has happened while i am using device. I have also found it this way after device not in use. No pattern as to cause.

## Device and OS

* Device: Pixel 5a non rooted
* Android version: 13
* Launcher version: v 0.9.3 
* Rom: CalyxOS 4.10.1 stable channel 

## Logcat

I dont know hiw to do this but i could probably get it done if linked to instructions.

P.s. great launcher i love it!

**Comment by machiav3lli** [comment]
Duplicate #337

**Comment by pleadeis** [comment]
Ok, is there any work around or just wwit for next release? I dont use seedvault or weather apps or too big widgets or any of these other things. 

Thank you.

**Comment by machiav3lli** [comment]
Do you have desktop lock active?

**Comment by pleadeis** [comment]
Nope I never use it.
