### ISSUE TITLE
All desktop icons disappeared

### ISSUE THREAD

**Issue by andreapx** [NeoApplications/Neo-Launcher#385]
## Description
I've unlocked the smartphone and all the apps icons on the desktop were gone, as well as the dock icons.
In the desktop I have just 3 icons: Gmail, Photos and Play Store.
It seems that Neo Launcher got reset.
Is there a way to restore the icons?
I've already rebooted, but nothing.

## Expected Behavior
See all the icons and desktop pages as before

## Actual Behavior
Clicking on the home button (or opening the app Neo Launcher, I see just 3 apps and no desktop pages

## Steps to Reproduce
I don't know, I just unlocked the smartphone as I always do

## Device and OS

* Device: Pixel 7
* Android version: Android 13
* Launcher version: 0.9.3
* Rom: stock

**Comment by saulhdev** [comment]
Did you changed the rows or columns?

**Comment by andreapx** [comment]
> Did you changed the rows or columns?

Nope, I did exactly nothing apart from unlock the phone

**Comment by machiav3lli** [comment]
then it's a #337 duplicate

**Comment by Turhvjbufv** [comment]
@machiav3lli close this as not planned not as completed it can cause confusion
