### ISSUE TITLE
[Feature Request] Material You Accent Color in Settings.

### ISSUE THREAD

**Issue by Cyanide-1** [NeoApplications/Neo-Launcher#393]
As my request says, material you should be implemented into the "accent color" area in the settings.

**Comment by machiav3lli** [comment]
Already implemented in the upcoming v1.0.0
![Screenshot_20230905-020402](https://github.com/NeoApplications/Neo-Launcher/assets/40302595/8300d6c5-9ca9-4780-860f-bda0e0cc489a)

**Comment by Cyanide-1** [comment]
oh ok, thank you
