### ISSUE TITLE
Setting for folder background transparency

### ISSUE THREAD

**Issue by A-7666** [NeoApplications/Neo-Launcher#407]
## Description
Add setting for folder background transparency (folders on desktop, folders in menu).

## Expected Behavior
Being able to configure folder transparency

## Actual Behavior
No such setting

## Steps to Reproduce

-

## Device and OS

* Android version: GrapheneOS, AOSP 13
* Launcher version: v0.9.3

**Comment by saulhdev** [comment]
Duplicate #408

**Comment by saulhdev** [comment]
this feature is already added on the current dev branch. 
Added in commit b631a8f
