### ISSUE TITLE
Choosing the "square" icon shape causes drawer search bar to become square after launcher restart

### ISSUE THREAD

**Issue by JimmyCushnie** [NeoApplications/Neo-Launcher#413]
## Description

If you choose the "square" icon shape, and then restart Neo Launcher, the search bar in the drawer will become square too.

This doesn't seem to be intended behavior. It doesn't happen with any other icon shapes.

## Expected Behavior

Drawer search bar shape is unaffected by icon shape preference.

## Actual Behavior

Drawer search bar shape changes after app restart when switching to Square icon shape.

## Steps to Reproduce

1. Fresh install of Neo Launcher 0.9.3. App icons are round; drawer search bar is round.
2. Change icon shape to 'square'
3. Return to the drawer. App icons are now square, and drawer search bar is still round.
4. Restart the launcher app. Drawer search bar has become square!!

![search bar bug](https://github.com/NeoApplications/Neo-Launcher/assets/32693298/21ad9b08-764b-4a64-a22c-95b2fb05bbad)

## Device and OS

* Device: Jelly Star
* Android version: 13.0
* Launcher version: 0.9.3; apk downloaded from the Github Releases
* Rom: Stock

**Comment by saulhdev** [comment]
That was the expected behavior. on that version the searchbar follows the icon appearance to apply the radius.
you can override the radius by change the search radius preference and set more than 0 in Settings > Search > Searchbar radius.
