### ISSUE TITLE
Quick switch

### ISSUE THREAD

**Issue by Turhvjbufv** [NeoApplications/Neo-Launcher#424]
Does neo launcer supporet quick switch? If it doesn't can you add support for it?

**Comment by machiav3lli** [comment]
We have actually a note about this in the TG group:

> I repeat myself. We are ignoring the Quickstep issues as we don't see that it has a future (Google seems to be aware of that since A11 integrates the Quickstep again(like pre-A9 more in the system)

That said, Quickstep (the real name of the recents manager) is already dropped from the A13-base and forward. This also helped to remove dependence on some pre-compiled frameworks.

**Comment by Turhvjbufv** [comment]
Thanks didn't notice
