### ISSUE TITLE
Space between apps icon and label is too close with high grid row size

### ISSUE THREAD

**Issue by squivix** [NeoApplications/Neo-Launcher#443]
When the number of rows in the grid size is high the app labels look uncomfortably close to the app icons. It would be nice to adjust this space between them automatically or add an option to adjust it manually.

## Expected Behavior

It should give enough space between label and icon so as not to look bad.

## Actual Behavior

Here's a screenshot:
<img src="https://github.com/NeoApplications/Neo-Launcher/assets/55770995/5e0341a4-4c75-445d-aad0-db656d871eac" width="400">

## Steps to Reproduce

1. Set grid size in settings to 10 by 5
2. Do not hide icon labels in home screen
3. Look at home screen

## Device and OS

* Device: Pixel 7
* Android version: 14
* Launcher version: 0.9.3
* Rom: Evolution X

**Comment by machiav3lli** [comment]
I don't see how space can be generated out of no where… 10x5 means each item have half of the height compared to the default 5x5. You have to either make icons or text smaller and everything should work with this density.
