### ISSUE TITLE
Notification permissions being blocked 

### ISSUE THREAD

**Issue by oniGino** [NeoApplications/Neo-Launcher#447]
Running your latest stable 0.7.3 on pixel with android 14 and notifications permissions are being blocked not sure why

Works fine in lawnchair FWIW 

![Screenshot_20240126-204706.png](https://github.com/NeoApplications/Neo-Launcher/assets/33404137/76fe5b91-c82e-4191-8121-86a18fd03ccf)

**Comment by Dzrknsd** [comment]
To fix this download the app from F-droid - IzzyOnDroid repo

**Comment by oniGino** [comment]
I figured it out if you hit the dots in the permissions menu. There is an option to enable that. It's an android 14 new permission

**Comment by Dzrknsd** [comment]
Oh ok, I have that on Android 13 but didn't see options for it

**Comment by machiav3lli** [comment]
Do you have Gapps (google services) or is it de-googled? I'm not sure if it's some security "feature" of google that should be disabled somewhere. As I don't face this on my device A14 & microG.

And to be sure of one thing, you mean 0.9.3 and not 0.7.3 right?

**Comment by oniGino** [comment]
Yes 0.9.3 this is a factory pixel 8 and it's a new android 14 security feature



https://stackoverflow.com/questions/77324695/how-to-enable-android-14-accessibility-restricted-setting
