### ISSUE TITLE
Some app icons looks blurry

### ISSUE THREAD

**Issue by Alihassan325** [NeoApplications/Neo-Launcher#452]
Hi 

Thanks for this app, I have tried it and it works great.
However in latest versions (0.9.3 & 0.9.2)
I found that some icons looks blurry, this issue is not in previous versions

Also a little request can you add feature to arrange apps in horizontal or alphabetical order like in MC Launcher

Thanks

**Comment by saulhdev** [comment]
Fixed in the v1.0.0 alpha
