### ISSUE TITLE
[Feature Request] Add Option to Automatically Add New Installs as Shortcuts to Desktop

### ISSUE THREAD

**Issue by RyanKoech** [NeoApplications/Neo-Launcher#461]
## Description
Just a suggestion, add option to automatically add new installations as shortcuts to desktop

## Expected Behavior
When turned on, newly installed apps are added to desktop shortcuts 

## Actual Behavior
No option to automatically add new installations as shortcuts to desktop

**Comment by saulhdev** [comment]
go to settings > Desktop > Add app icon to home screen
