### ISSUE TITLE
Flag alpha as needing clean install

### ISSUE THREAD

**Issue by Turhvjbufv** [NeoApplications/Neo-Launcher#476]
As a lot of people will probably just update, or use obtainium, it will ruin their current neo launcher configuration

**Comment by Ionshard** [comment]
Can confirm, Obtanium automatically updated to alpha. Neo launcher immediately started crash looping. Needed to uninstall and reinstall, lost all settings. Might be good for info on the proper way to upgrade...

**Comment by abacao** [comment]
I was affected by this... Boot loop, constant crashing

**Comment by machiav3lli** [comment]
Got it labelled as pre-release for now.

**Comment by bonswouar** [comment]
Did you end up removing this release completely? I don't see it anymore in the pre-releases

_As a new Neo Launcher user I can say it works pretty great for an alpha! I've only noticed an UX issue when renaming apps in the drawer, but otherwise it's already my favourite launcher :)_
