### ISSUE TITLE
App search in drawer fails for apps with special characters in their name

### ISSUE THREAD

**Issue by Lanchon** [NeoApplications/Neo-Launcher#487]
## Description
app search in drawer fails for certain apps. it seems to be triggered by special characters in the app name.

## Expected Behavior
app should be found.

## Actual Behavior
app is not found.

## Steps to Reproduce
1. install official F-Droid client app: https://f-droid.org/F-Droid.apk
2. try looking for it in the drawer.

## Device and OS
self-built OS based on lineageos 20.

## Logcat
n/a.

**Comment by lameventanas** [comment]
This doesn't happen to me with F-Droid, but it does happen with the Japanese version of Mercari (com.kouzoh.mercari).

**Comment by Lanchon** [comment]
this now works for the case of F-Droid. so closing.
