### ISSUE TITLE
F-Droid repo

### ISSUE THREAD

**Issue by nonaybay** [NeoApplications/Neo-Launcher#60]
<h3>Omega Launcher F-Droid repositories</h3>
<h4>The https://raw.githubusercontent.com/rafaelvenancio98/fdroid/master/fdroid/repo repository has been discontinued</h4>
<br/>
<p><a href="https://raw.githubusercontent.com/nonaybay/newomega/master/fdroid/repo">https://raw.githubusercontent.com/nonaybay/newomega/master/fdroid/repo</a></p>

**Comment by Sitavi** [comment]
It doesn't seems to work : 404: Not Found

**Comment by Sitavi** [comment]
@mirdaki Strange, it didn't worked for me :/

**Comment by mirdaki** [comment]
![Screenshot_20211006-143710_Aurora_Droid](https://user-images.githubusercontent.com/8786151/136287479-633f8d97-9271-426e-9df3-f7edfa355bb6.png)

Try this QR Code? Auroa Droid (the F-Droid client I use) was able to connect

**Comment by nonaybay** [comment]
[](https://t.me/omegalauncher_group/5273)
