### ISSUE TITLE
v0.8.0 crashes on start on Android 11

### ISSUE THREAD

**Issue by l3u** [NeoApplications/Neo-Launcher#85]
I just wanted to check out the new 0.8.0 release, but it crashes while starting on Android 11 on my Nokia 4.2. I only see "The app crashed repeatedly, sorry for the inconvenience". After deinstalling it and installing 0.7.1 again, I can at leat use my phone again (though the settings are obviously lost of course ;-)

How can I help to debug this? Is there a way to get a backtrace, although the program doesn't even start?

**Comment by machiav3lli** [comment]
Did you update from 0.7.1 to 0.8.0? Then try installing 0.8.0 directly

**Comment by l3u** [comment]
Thanks for the hint, after deinstalling Omega 0.7.1 and installing 0.8.0 afterwards, it starts.

**Comment by KrisadaFantasy** [comment]
Updated from 0.7.1 and had this too. Clear storage, but no clear cache, also solve this problem.

**Comment by aaronhatesregex** [comment]
0.8.0 managed to screw up my two phones XD (Android 8.0 and 11.0). Clearing data sovles the issue.
A sidenote: DON'T try to *restore backup* when you rescue your ruined os, or the nightmare will reoccur 👻.

**Comment by saulhdev** [comment]
the base code has been rebased on v0.9.0
