### ISSUE TITLE
Android gesture navigation broken

### ISSUE THREAD

**Issue by chaptergy** [NeoApplications/Neo-Launcher#96]
## Description

The native Android [gesture navigation pill](https://support.google.com/android/answer/9079644) does not work at all on the omega home screen. When setting your android navigation from 3-button or 2-button to gesture, you are not able to do anything. It does not open the multitasking screen, it does not allow you to go home (if it isn't set as the launcher), it does not allow you to open the assistant app by swiping up from a corner, it does not allow you to do anything.

## Expected Behavior

You are able to normally navigate using the native android navigation.

## Actual Behavior

It just does nothing. Only the edge-swipe to go back seems to work.

## Steps to Reproduce

1. Set your launcher to something other than omega 
2. Change your navigation style to gesture
3. Open omega
4. Try to open the multitasking using the native navigation

## Device and OS

* Device: Pixel 4a
* Android version: 11
* Launcher version: 0.8.0
* Rom: CalynxOS

**Comment by chaptergy** [comment]
It seems this is only an issue as long as the app is not the default launcher. So not sure how pressing this issue is.

**Comment by superiums** [comment]
Yes, set it as default launcher solved this issue.
