### ISSUE TITLE
Chrome has generic internet icov

### ISSUE THREAD

**Issue by refi64** [NeoApplications/Neo-Launcher#97]
## Description

For reasons unknown to me, the Chrome icon looks like this:

![Screenshot_20210723-000951](https://user-images.githubusercontent.com/1690697/126739721-64b342cd-4b7e-40b3-8cb4-ee068c60ba27.png)

No icon packs have been selected (or are installed). All other icons appear to look fine.

## Expected Behavior

The icon should be the pretty Chrome icon.

## Actual Behavior

The icon looks half a decade old.

## Steps to Reproduce

1. Start Omega

## Device and OS

* Device: Google Pixel 4XL
* Android version: 11
* Launcher version: 0.8.0
* Rom: Stock

**Comment by siodor** [comment]
I can confirm this problem.

- Device: Fairphone 4
- Android version: 11
- Launcher version: 0.8.1
- Rom: Stock

**Comment by machiav3lli** [comment]
You sure it's not an issue on Chrome's side? We don't mask the icon provided from the system, ruther just form it into the chosen form.

**Comment by sheckandar** [comment]
Just found this launcher today and the problem with Chrome icon is there. I tried changing the icon to anything else, even some random icon, but it never changes, no matter what I try.

**Comment by saulhdev** [comment]
Fixed on v0.9.0
